const types = {
  ADD_FIGHTER: "ADD_FIGHTER",
  DEL_FIGHTER: "DEL_FIGHTER",
  GET_FIGHTER: "GET_FIGHTER",
  SET_SECOND_EDAP: "SET_SECOND_EDAP",
  SET_THIRD_EDAP: 'SET_THIRD_EDAP',
  SET_COUNT: 'SET_COUNT',
  POLUFINAL: "POLUFINAL",
  FINAL: "FINAL",
  MIDDLE: "MIDDLE",
  MIDDLE3: "MIDDLE3",
  WINNERS: "WINNERS",
  EMPTY:'EMPTY'

}
export default types